scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'java_application'
    metrics_path: /actuator/prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:9000"]
