server.port: 9000
spring:
  application:
    name: kuke-board-article-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/article
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  kafka:
    bootstrap-servers: 127.0.0.1:9092

management:
  endpoints:
    web:
      exposure:
#        include: "health,info,prometheus"
        include: prometheus
#  endpoint:
#    health:
#      show-details: "always"
  metrics:
    tags:
      application: ${spring.application.name:demo}
      profile: ${spring.profiles.active:local}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms,100ms,250ms,500ms,1s,2s

